---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t tomcat-image:latest .
    args:
      chdir: /opt/k8s

  - name: create tag to image
    command: docker tag tomcat-image satyaranjan87/tomcat-image

  - name: push image on to dockerhub
    command: docker push satyaranjan87/tomcat-image

  - name: remove docker images form ansible server
    command: docker rmi tomcat-image:latest satyaranjan87/tomcat-image
    ignore_errors: yes
